#---------------------- Spring properties Default ---------------------------                 
spring:
  application:
    name: web-service  # Identify this application
    
# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port    
  
remote: 
  endpoint: http://0794baa3.ngrok.io

image:
  capture: false
  dir:  /home/pi/demo/

audio:
  sirenFilepath: /Users/kxu/Downloads/siren-cut.mp3
  whistleFilepath: /Users/kxu/Downloads/whistle.mp3

aws: 
  bucket: dummy_cache
  accesskey: AKIAJQUHVN6KWRWCSFFQ
  secretkey: M45CkBehcWunQAvj7+6GG8syMlHfyCWnybLN5glI
---

#---------------------- Spring properties QA -------------------------------
spring:
    profiles: HUB
  
image:
  capture: true
  dir:  /home/pi/demo/
---


#---------------------- Spring properties PROD -------------------------------
spring:
    profiles: DEVICE

